language: ruby
rvm:
  - 2.3.1

env:
  - RAILS_ENV="test"

install:
  - 'bundle install --without production'

before_script:
    - 'bundle exec rake db:migrate RAILS_ENV="test"'

script: 'bundle exec rake test'
